#!/bin/bash

docker run \
    --name caddy \
    -v "$(pwd)/Caddyfile:/etc/Caddyfile" \
    -v "$HOME/.caddy:/root/.caddy" \
    -v /opt/www:/opt/www \
    -e ACME_AGREE=true \
    --net host \
    --restart always \
    -d \
    abiosoft/caddy

